name: ci-workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "running tests for both push and pull requests"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - run: echo "deploying app - this only runs on a direct push, not a PR"
